# Generated by Django 4.1.2 on 2022-10-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userprofile',
        ),
    ]
