# Generated by Django 4.1.2 on 2022-11-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
