# Generated by Django 4.1.2 on 2022-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product')),
                ('price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
