# Generated by Django 4.1.2 on 2022-11-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'Topwear'), ('B', 'Bottomwear'), ('E', 'Elctronic'), ('M', 'Mobile')], max_length=5, null=True),
        ),
    ]
